services:
  - type: web
    name: sylva-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: false  # Désactivé car on déclenche via webhook
    healthCheckPath: /test
    envVars:
      - key: APP_NAME
        value: Sylva App
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromService:
          type: web
          name: sylva-app
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: sylva-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sylva-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: sylva-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: sylva-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sylva-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: single
      - key: LOG_LEVEL
        value: error
      - key: MAIL_MAILER
        value: log

databases:
  - name: sylva-db
    databaseName: laravel
    user: laravel_user
    plan: free